# Домашнее задание к лекции "Функции"
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}
Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

In [339]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

## Задание 1
### Пункт 1.
Пользователь по команде "p" может узнать владельца документа по его номеру
Примеры работы:

1.

Введите команду:
p

Введите номер документа:
10006
Результат:
Владелец документа: Аристарх Павлов

2.

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [198]:
def doc_num():
    doc_num = input('Введите номер документа: ')
    return doc_num

In [226]:
doc_num()

Введите номер документа: 10006


'10006'

In [199]:
def number_doc(doc_):
    
    list_doc = []
    for doc_l in doc_:
        if doc_l['number'] not in list_doc:
            list_doc.append(doc_l['number'])
    
    user_input_1 = doc_num()
    
    if user_input_1 not in list_doc:
        print('Документ не найден в базе')
        
    for doc in doc_:
        if doc['number'] == user_input_1:
            print(f'Владелец документа: {doc["name"]}') 

In [229]:
number_doc(documents)

Введите номер документа: 123
Документ не найден в базе


### Пункт 2.
Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
Примеры работы:

1.

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

2.

Введите команду:
s

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [200]:
def doc_shelf(dir_):
    user_input_3 = doc_num()
    i = 0    
    for direct, num in dir_.items():        
        if user_input_3 in num:
             print(f'Документ хранится на полке: {direct}')
        else:
            i += 1 
    if i == len(dir_):
        print('Документ не найден в базе')

In [233]:
doc_shelf(directories)

Введите номер документа: 123
Документ не найден в базе


## Пункт 3.
Пользователь по команде "l" может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l
Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1

№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [201]:
def all_info(doc_, dir_):
    for i in doc_:
        for t, m in dir_.items():
            if i['number'] in m:
#            print (t)
                print(f"№: {i['number']}, тип: {i['type']}, владелец: {i['name']}, полка хранения: {t}")

In [235]:
all_info(documents, directories)

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


## Пункт 4. 
Пользователь по команде "ads" может добавить новую полку

Примеры работы:

1.

Введите команду:
ads

Введите номер полки:
10

Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

2.

Введите команду:
ads

Введите номер полки:
1

Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [202]:
def num_shelf():
    num_shelf = input('Введите номер полки:')
    return num_shelf

In [2]:
num_shelf()

Введите номер полки:5


'5'

In [203]:
def add_shelf(dir_):
    user_input_2 = num_shelf()
    if user_input_2 in dir_:
        print('Такая полка уже существует. Текущий перечень полок: ' + ", ".join(map(str,dir_.keys())))
    else:
        dir_[user_input_2] = []
        print('Полка добавлена. Текущий перечень полок: ' + ", ".join(map(str,dir_.keys()))) 


In [124]:
add_shelf(directories)

Введите номер полки:3
Такая полка уже существует. Текущий перечень полок: 1, 2, 3


## Пункт 5. 
Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

Введите команду:
ds

Введите номер полки:
3

Результат:
Полка удалена. Текущий перечень полок: 1, 2.

2.

Введите команду:
ds

Введите номер полки:
1

Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

3.

Введите команду:
ds

Введите номер полки:
4

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [204]:
def del_shelf(dir_):
    user_input_3 = num_shelf()
    if user_input_3 in dir_:
        if dir_[user_input_3] == []:
            del(dir_[user_input_3])
            print('Полка удалена. Текущий перечень полок: ' + ", ".join(map(str,dir_.keys())))
        else:
            print('На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: ' + ", ".join(map(str,dir_.keys())))
    else:
        print('Такой полки не существует. Текущий перечень полок: ' + ", ".join(map(str,dir_.keys())))

In [70]:
del_shelf(directories)

Введите номер полки:10
Такой полки не существует. Текущий перечень полок: 1, 2, 3


# Задание 2 (необязательное)
Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

## Пункт 1. 
Пользователь по команде "ad" может добавить новый документ в данные
Примеры работы:

1.

Введите команду:
ad

Введите номер документа:
42

Введите тип документа:
multipassport

Введите владельца документа:
R2D2

Введите полку для хранения:
3

Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
2.

Введите команду:
ad

Введите номер документа:
42

Введите тип документа:
multipassport

Введите владельца документа:
R2D2

Введите полку для хранения:
4

Результат:

Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [300]:
def add_doc(doc_, dir_):
    doc_num_ = doc_num()
    doc_type = input('Введите тип документа: ')
    doc_name = input('Введите владельца документа: ')
    num_shelf_ = num_shelf()
    if num_shelf_ in dir_:
        documents.append({'type': doc_type, 'number': doc_num_, 'name': doc_name})
        for keys, list_ in dir_.items():
            if keys == num_shelf_:
                list_.append(doc_num_)
        print('Документ добавлен. Текущий список документов: ')
        all_info(doc_, dir_)
    else:
        print('Такой полки не существует. Добавьте полку командой as.', 'Текущий список документов: ', sep = "\n")
        all_info(doc_, dir_)
#    print(doc_)
#    print(dir_)
    


In [301]:
add_doc(documents, directories)

Введите номер документа: 123
Введите тип документа: 12
Введите владельца документа: 1
Введите номер полки:1
Документ добавлен. Текущий список документов: 
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 123, тип: 12, владелец: 1, полка хранения: 1


## Пункт 2. 
Пользователь по команде "d" может удалить документ из данных

Примеры работы:

1.

Введите команду:
d

Введите номер документа:
10006

Результат:

Документ удален. 

Текущий список документов:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

2.

Введите команду:
d

Введите номер документа:
123456

Результат:

Документ не найден в базе. 

Текущий список документов:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [222]:
def del_doc(doc_, dir_):
    doc_num_ = doc_num()
    x = 0
    for num_ in doc_:
#        x = 0
        if doc_num_ == num_['number']:
        
            for num in doc_:
                if doc_num_ == num['number']:
                    del(doc_[doc_.index(num)])

            for shelf in dir_.values():
                if doc_num_ in shelf:
                    shelf.remove(doc_num_)
            print('Документ удален.', 'Текущий список документов:', sep = "\n") 
            all_info(doc_, dir_)
        else:
            x += 1
#    print (x)
    if x == len(doc_):
        print('Документ не найден в базе.', 'Текущий список документов:', sep = "\n")
        all_info(doc_, dir_)

In [223]:
del_doc(documents, directories)

Введите номер документа: 123
Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


## Пункт 3. 
Пользователь по команде "m" может переместить документ с полки на полку
Примеры работы:

1.

Введите команду:
m

Введите номер документа:
11-2

Введите номер полки:
3

Результат:

Документ перемещен.

Текущий список документов:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

2.

Введите команду:
m

Введите номер документа:
11-2

Введите номер полки:
10

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

3.

Введите команду:
m

Введите номер документа:
42

Введите номер полки:
2

Результат:

Документ не найден в базе. 

Текущий список документов:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [342]:
def move_doc(doc_, dir_):
    
    doc_num_ = doc_num()
    num_shelf_ = num_shelf()
    
    x = 0
    y = 0

    for num in doc_:
        if doc_num_ == num['number']:
            if num_shelf_ in dir_:
                for key_, list_ in dir_.items():
                    if key_ == num_shelf_:
                        list_.append(doc_num_)
                    elif doc_num_ in list_:
                        list_.remove(doc_num_)      
                print('Документ перемещен.', 'Текущий список документов:', sep = "\n")
                all_info(doc_, dir_)
            else:
                print('Такой полки не существует. Текущий перечень полок:' + ", ".join(map(str,dir_.keys())))        
        else:
            y += 1
    if y == len(doc_):
        print('Документ не найден в базе.', 'Текущий список документов:', sep = "\n")
        all_info(doc_, dir_)


In [257]:
def main(doc_, dir_):
    while True:
        user_input = input('Введите команду: ')
        if user_input == 'p':
            number_doc(doc_)
        elif user_input == 's':
            doc_shelf(dir_)
        elif user_input == 'l':
            all_info(doc_, dir_)
        elif user_input == 'ads':
            add_shelf(dir_)
        elif user_input == 'ds':
            del_shelf(dir_)
        elif user_input == 'ad':
            add_doc(doc_, dir_)
        elif user_input == 'd':
            del_doc(doc_, dir_)
        elif user_input == 'm':
            move_doc(doc_, dir_)
        elif user_input == 'q':
            print('До свидания')
            break 
                         
            

In [343]:
main(documents, directories)

Введите команду: m
Введите номер документа: 10006
Введите номер полки:10
Такой полки не существует. Текущий перечень полок:1, 2, 3
Введите команду: m
Введите номер документа: 10006
Введите номер полки:3
Документ перемещен.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
Введите команду: m
Введите номер документа: 10006
Введите номер полки:2
Документ перемещен.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду: m
Введите номер документа: 123
Введите номер полки:1
Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 